# -*- coding: utf-8 -*-
"""Code.v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lQjbgTCn1syUGlX2CXuPfO-K-heyTWH

#CẤU HÌNH HỆ THỐNG VÀ GIẢI NÉN DỮ LIỆU
"""

import cv2
import numpy as np
import os
import zipfile
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from google.colab import files

#CẤU HÌNH ĐẦU VÀO

ZIP_FILENAME = 'Dataset tranh.zip'
EXTRACT_PATH = '/content/dataset_extracted'

TEST_IMAGE_NAME = 'test.jpg'

print(" Start to run...")

"""##1. Giải nén dữ liệu"""

if os.path.exists(ZIP_FILENAME):
    print(f"--> Đã tìm thấy file '{ZIP_FILENAME}'. Đang giải nén...")
    with zipfile.ZipFile(ZIP_FILENAME, 'r') as zip_ref:
        zip_ref.extractall(EXTRACT_PATH)
    print("--> Giải nén thành công!")
else:
    print(f"Không tìm thấy file '{ZIP_FILENAME}'. Vui lòng upload file zip vào mục Files.")

"""##2. Tự động tìm đường dẫn gốc chứa ảnh"""

def find_data_root(start_path):
    for root, dirs, files in os.walk(start_path):
        for d in dirs:
            # Tìm thư mục đặc trưng của Nguyễn Gia Trí để xác định gốc
            if "NguyenGiaTri" in d or "1.jpg" in d:
                return root
    return start_path

BASE_PATH = find_data_root(EXTRACT_PATH)
print(f"--> Đường dẫn gốc dữ liệu: {BASE_PATH}")

"""##3. Định nghĩa thông tin"""

dataset_config = {
    "NguyenGiaTri": {
        "keywords": ["NguyenGiaTri", "1.jpg"],
        "label": 1,
        "name": "Nguyễn Gia Trí",
        "style": "Sơn mài (Vàng son, then, vỏ trứng - Gam màu nóng, trầm)",
        "avg_edge": 0, # Sẽ cập nhật sau
        "path": None
    },
    "NguyenTuongLan": {
        "keywords": ["NguyenTuongLan", "2.jpg"],
        "label": 2,
        "name": "Nguyễn Tường Lân",
        "style": "Đa phong cách (Huyền ảo, thơ mộng, gam màu nhẹ)",
        "avg_edge": 0,
        "path": None
    },
    "ToNgocVan": {
        "keywords": ["ToNgocVan", "3.jpg"],
        "label": 3,
        "name": "Tô Ngọc Vân",
        "style": "Sơn dầu (Lãng mạn, ánh sáng phương Tây, gam trắng/xanh)",
        "avg_edge": 0,
        "path": None
    },
    "TranVanCan": {
        "keywords": ["TranVanCan", "4.jpg"],
        "label": 4,
        "name": "Trần Văn Cẩn",
        "style": "Hiện thực (Khắc gỗ, nét khỏe, mảng màu phẳng)",
        "avg_edge": 0,
        "path": None
    }
}

#Tự động map đường dẫn vào thực tế config

from os.path import exists
for key, config in dataset_config.items():
  if os.path.exists(BASE_PATH):
    for item in os.listdir(BASE_PATH):
            if any(k in item for k in config["keywords"]) and os.path.isdir(os.path.join(BASE_PATH, item)):
                config["path"] = os.path.join(BASE_PATH, item)
                print(f" Đã nạp dữ liệu: {config['name']}")
                break

"""TRÍCH XUẤT ĐẶC TRƯNG CỦA DỮ LIỆU"""

def calculate_edge_density(img):
    """Tính mật độ đường nét (brushwork complexity)"""
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Dùng Canny để tìm cạnh (nét vẽ)
    edges = cv2.Canny(gray, 100, 200)
    # Tính tỷ lệ pixel cạnh trên tổng số pixel
    density = np.sum(edges) / (img.shape[0] * img.shape[1])
    return density

def extract_features(image_path, k=5):
    """
    Hàm cốt lõi: Đọc ảnh -> Resize -> K-Means Clustering -> Lấy bảng màu
    """
    img = cv2.imread(image_path)
    if img is None: return None

    # 1. Tính độ phức tạp đường nét (để phân tích thêm)
    edge_density = calculate_edge_density(img)

    # 2. Xử lý màu sắc
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img_small = cv2.resize(img_rgb, (100, 100))
    pixels = img_small.reshape(-1, 3)

    # Dùng K-Means để tìm k màu đại diện
    kmeans = KMeans(n_clusters=k, n_init=10, random_state=42)
    kmeans.fit(pixels)

    colors = kmeans.cluster_centers_
    labels = kmeans.labels_

    counts = np.bincount(labels)
    proportions = counts / len(pixels)

    sorted_idx = np.argsort(proportions)[::-1]
    sorted_colors = colors[sorted_idx]
    sorted_props = proportions[sorted_idx]

    # Tạo vector đặc trưng màu: [R1, G1, B1, %1, R2, G2, B2, %2, ...]
    feature_vector = []
    for i in range(k):
        feature_vector.extend(sorted_colors[i])
        feature_vector.append(sorted_props[i])

    return np.array(feature_vector), edge_density

"""#CHẠY QUYÉT DỮ LIỆU"""

X_data = [] # Chứa vector đặc trưng màu
y_labels = [] # Chứa nhãn (1, 2, 3, 4)
raw_stats = {"sizes": [], "edges": {1:[], 2:[], 3:[], 4:[]}}

print("\n Đang phân tích màu sắc và đường nét từng bức tranh...")

for key, config in dataset_config.items():
    if config["path"]:
        for f in os.listdir(config["path"]):
            if f.lower().endswith(('.jpg', '.png', '.jpeg')):
                fpath = os.path.join(config["path"], f)

                # Thu thập thông tin kích thước cho EDA
                img_temp = cv2.imread(fpath)
                if img_temp is not None:
                    raw_stats["sizes"].append(img_temp.shape[:2])

                # Trích xuất đặc trưng
                feats, edge_score = extract_features(fpath, k=5)
                if feats is not None:
                    X_data.append(feats)
                    y_labels.append(config["label"])
                    raw_stats["edges"][config["label"]].append(edge_score)

# Tính trung bình độ phức tạp nét vẽ cho từng họa sĩ
for lbl, scores in raw_stats["edges"].items():
    avg = np.mean(scores) if scores else 0
    # Map ngược lại vào config
    for key, val in dataset_config.items():
        if val["label"] == lbl:
            dataset_config[key]["avg_edge"] = avg

X_data = np.array(X_data)
y_labels = np.array(y_labels)
print(f" Hoàn tất! Đã học được {len(X_data)} tác phẩm.")

"""#HUẤN LUYỆN MÔ HÌNH"""

if len(X_data) > 0:
    # Sử dụng KNN với weights='distance'
    knn = KNeighborsClassifier(n_neighbors=min(5, len(X_data)), weights='distance')
    knn.fit(X_data, y_labels)
    print(" Mô hình AI đã được huấn luyện xong (Dựa trên hệ màu).")
else:
    print(" LỖI: Không có dữ liệu để huấn luyện.")

"""#DỰ ĐOÁN VÀ PHÂN TÍCH ẢNH TEST"""

def analyze_and_predict(image_path):
    print("\n" + "="*50)
    print(f"PHÂN TÍCH BỨC TRANH: {image_path}")
    print("="*50)

    if not os.path.exists(image_path):
        print(" Không tìm thấy file ảnh test. Hãy kiểm tra lại tên file.")
        return

    # 1. Hiển thị ảnh gốc
    img = cv2.imread(image_path)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # 2. Lấy đặc trưng
    input_feats, input_edge = extract_features(image_path, k=5)

    # 3. Dự đoán
    pred_label = knn.predict([input_feats])[0]
    probs = knn.predict_proba([input_feats])[0]

    # 4. Lấy thông tin kết quả
    result_info = None
    for k, c in dataset_config.items():
        if c["label"] == pred_label:
            result_info = c
            break

    print(f" KẾT LUẬN: Tranh mang phong cách của {result_info['name'].upper()}")
    print(f"Phong cách điển hình: {result_info['style']}")
    print(f" Độ tin cậy (Màu sắc): {probs[pred_label-1]*100:.2f}%")

    # So sánh đường nét
    print(f" Phân tích nét vẽ :")
    print(f"   - Tranh này: {input_edge:.2f}")
    print(f"   - Trung bình của {result_info['name']}: {result_info['avg_edge']:.2f}")
    if abs(input_edge - result_info['avg_edge']) < 10:
        print("   => Tương đồng về độ phức tạp nét vẽ.")
    else:
        print("   => Khác biệt về độ phức tạp nét vẽ (Lưu ý: Mô hình chủ yếu dựa vào màu sắc).")

    # Plotting
    plt.figure(figsize=(14, 5))
    plt.subplot(1, 3, 1)
    plt.imshow(img_rgb)
    plt.title("Ảnh Input")
    plt.axis('off')

    # Bảng màu
    plt.subplot(1, 3, 2)
    palette_bar = np.zeros((50, 300, 3), dtype="uint8")
    curr_x = 0
    for i in range(0, len(input_feats), 4):
        color = input_feats[i:i+3]
        prop = input_feats[i+3]
        end_x = curr_x + int(prop * 300)
        palette_bar[:, curr_x:end_x] = color
        curr_x = end_x
    plt.imshow(palette_bar)
    plt.title("Bảng màu đặc trưng (K-Means)")
    plt.axis('off')

    # Biểu đồ xác suất
    plt.subplot(1, 3, 3)
    names = [c["name"] for k, c in dataset_config.items()]
    y_pos = np.arange(len(names))
    plt.barh(y_pos, probs, color='skyblue')
    plt.yticks(y_pos, names)
    plt.xlabel("Độ tương đồng màu sắc")
    plt.title("So sánh tương đồng")

    plt.tight_layout()
    plt.show()

analyze_and_predict(TEST_IMAGE_NAME)

#ĐÁNH GIÁ MÔ HÌNH

def perform_eda():
    print(" PHÂN TÍCH DỮ LIỆU (EDA) & ĐÁNH GIÁ ĐỘ CHÍNH XÁC")

    if len(X_data) == 0: return

    # 1. Thống kê số lượng
    unique, counts = np.unique(y_labels, return_counts=True)
    names = [c["name"] for c in dataset_config.values()]

    plt.figure(figsize=(12, 4))
    plt.subplot(1, 3, 1)
    sns.barplot(x=names, y=counts, palette="viridis")
    plt.title("Số lượng tranh mỗi họa sĩ")
    plt.xticks(rotation=45)


    # 4. Chấm điểm độ chính xác
    print("\n--- ĐANG CHẤM ĐIỂM MÔ HÌNH (Cross-Validation 80/20) ---")
    X_train, X_test, y_train, y_test = train_test_split(X_data, y_labels, test_size=0.2, random_state=42, stratify=y_labels)

    val_knn = KNeighborsClassifier(n_neighbors=min(5, len(X_train)), weights='distance')
    val_knn.fit(X_train, y_train)
    y_pred = val_knn.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    print(f" ĐỘ CHÍNH XÁC TỔNG QUÁT: {acc*100:.2f}%")
    print("\nChi tiết báo cáo:")
    print(classification_report(y_test, y_pred, target_names=names))

    # Ma trận nhầm lẫn
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=names, yticklabels=names)
    plt.title("Ma trận nhầm lẫn (Confusion Matrix)")
    plt.xlabel("Máy dự đoán")
    plt.ylabel("Thực tế")
    plt.show()

# Chạy phân tích EDA
perform_eda()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import cv2
def visualize_dataset_analysis():
    print("TRỰC QUAN HÓA DỮ LIỆU DATASET (EDA)")

    if len(X_data) == 0:
        print(" Chưa có dữ liệu để vẽ. Vui lòng chạy phần trích xuất đặc trưng trước.")
        return

    # Thiết lập style cho biểu đồ đẹp hơn
    sns.set_style("whitegrid")

    # Lấy dữ liệu cần thiết
    unique, counts = np.unique(y_labels, return_counts=True)
    names = [c["name"] for c in dataset_config.values()]
    colors_map = ['#8c564b', '#e377c2', '#1f77b4', '#ff7f0e'] # Nâu, Hồng, Xanh, Cam

    # TẠO KHUNG VẼ LỚN (2 Hàng x 2 Cột)
    fig = plt.figure(figsize=(16, 10))
    fig.suptitle('PHÂN TÍCH ĐẶC ĐIỂM TRANH TỨ LÂN VÂN CẨN', fontsize=16, fontweight='bold')

    #  1. BIỂU ĐỒ TRÒN: TỶ LỆ SỐ LƯỢNG TRANH ---
    ax1 = fig.add_subplot(2, 2, 1)
    ax1.pie(counts, labels=names, autopct='%1.1f%%', startangle=140, colors=colors_map,
            wedgeprops={'edgecolor': 'white', 'linewidth': 2})
    ax1.set_title("1. Tỷ lệ phân bố dữ liệu trong Dataset", fontweight='bold')

    # 2. BIỂU ĐỒ HỘP: ĐỘ PHỨC TẠP NÉT VẼ (EDGE DENSITY) ---
    ax2 = fig.add_subplot(2, 2, 2)

    # Chuẩn bị dữ liệu cho Boxplot
    edge_data = []
    edge_labels = []
    for lbl, scores in raw_stats["edges"].items():
        edge_data.extend(scores)
        # Tìm tên họa sĩ tương ứng với label
        name = ""
        for k, c in dataset_config.items():
            if c["label"] == lbl: name = c["name"]
        edge_labels.extend([name]*len(scores))

    sns.boxplot(x=edge_labels, y=edge_data, palette=colors_map, ax=ax2)
    ax2.set_title("2. Độ phức tạp chi tiết/nét vẽ (Texture Complexity)", fontweight='bold')
    ax2.set_ylabel("Mật độ cạnh (Edge Density)")
    ax2.grid(True, linestyle='--', alpha=0.6)

    # 3. BIỂU ĐỒ TÁN XẠ: KÍCH THƯỚC ẢNH
    ax3 = fig.add_subplot(2, 2, 3)
    if raw_stats["sizes"]:
        h, w = zip(*raw_stats["sizes"])
        ax3.scatter(w, h, alpha=0.6, c='purple', s=50, edgecolors='w')
        ax3.set_title("3. Phân bố độ phân giải ảnh gốc", fontweight='bold')
        ax3.set_xlabel("Chiều rộng (Width)")
        ax3.set_ylabel("Chiều cao (Height)")
    else:
        ax3.text(0.5, 0.5, "Không có dữ liệu size", ha='center')

    #  4. DẢI MÀU TRUNG BÌNH
    ax4 = fig.add_subplot(2, 2, 4)
    ax4.axis('off')
    ax4.set_title("4. Bảng màu đặc trưng trung bình của từng họa sĩ", fontweight='bold')

    # Vẽ các dải màu con bên trong ax4
    y_offset = 0.8
    for idx, (key, config) in enumerate(dataset_config.items()):
        lbl = config["label"]
        # Lấy tất cả vector màu của họa sĩ này từ X_data
        artist_features = X_data[y_labels == lbl]

        if len(artist_features) > 0:
            # Tính trung bình cộng các vector đặc trưng
            mean_feature = np.mean(artist_features, axis=0)

            # Tách lại thành bảng màu (5 màu chủ đạo trung bình)
            mean_palette = []
            mean_props = []
            for i in range(0, len(mean_feature), 4):
                mean_palette.append(mean_feature[i:i+3]) # RGB
                mean_props.append(mean_feature[i+3])     # Tỷ lệ

            # Vẽ dải màu
            bar_x = 0
            bar_y = y_offset - (idx * 0.2)
            bar_height = 0.15

            # Label tên
            ax4.text(-0.1, bar_y + bar_height/2, config["name"],
                     va='center', ha='right', fontsize=10, fontweight='bold')

            # Vẽ từng đoạn màu
            current_x = 0
            for color, prop in zip(mean_palette, mean_props):
                # Chuẩn hóa màu về 0-1 để vẽ
                c_norm = np.array(color) / 255.0
                ax4.barh(bar_y, prop, left=current_x, height=bar_height, color=c_norm, edgecolor='none')
                current_x += prop

    plt.tight_layout()
    plt.show()

# Gọi hàm để vẽ
visualize_dataset_analysis()